web/mooctracker_rails/config/routes.rb
MooctrackerRails::Application.routes.draw do
  
  get "sessions/create"
  get "sessions/destroy"
  get 'auth/:provider/callback', to: 'sessions#create',  via: 'post'
  get 'auth/failure', to: redirect('/'), via: 'delete'
  get 'signout', to: 'sessions#destroy', as: 'signout', via: 'delete'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :courses
  resources :projects
  resources :students
  resources :users

  match "/api/currentuser", to: 'users#currentUser', via:'get'

  match "/api/studentcourse", to: 'studentcourses#index', via:'get'
  match "/api/studentcourse/:id", to: 'studentcourses#show', via:'get'
  match "/api/studentcourse/", to: 'studentcourses#create', via:'post'
  match "/api/studentcourse/:id", to: 'studentcourses#update', via:'put'
  match "/api/studentcourse/:id", to: 'studentcourses#destroy', via:'delete'

  match "/api/project", to: 'projects#index', via:'get'
  match "/api/project/:id", to: 'projects#show', via:'get'
  match "/api/project/", to: 'projects#create', via:'post'
  match "/api/project/:id", to: 'projects#update', via:'put'
  match "/api/project/:id", to: 'projects#destroy', via:'delete'

  match "/api/course", to: 'courses#index', via:'get'
  match "/api/course/:id", to: 'courses#show', via:'get'
  match "/api/course/", to: 'courses#create', via:'post'
  match "/api/course/:id", to: 'courses#update', via:'put'
  match "/api/course/:id", to: 'courses#destroy', via:'delete'

  match "/api/student/", to: 'students#create', via:'post'    
  match "/api/student", to: 'users#index', via:'get'
  match "/api/student/:id", to: 'users#show', via:'get'
  match "/api/student/:id", to: 'students#update', via:'put'
  match "/api/student/:id", to: 'students#destroy', via:'delete'

  match "/api/student/course/:id", to: 'studentcourses#showCourseToAdmin', via:'get'

  match "/api/student/project/:id", to: 'projects#showProjectToAdmin', via:'get'

  root to: "home#show"

end

web/mooctracker_rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  	@project = Project.new
    @course = Course.new
  end
end

web/mooctracker_rails/app/helpers/home_helper.rb
module HomeHelper
end

web/mooctracker_rails/app/views/home/show.html.erb
<% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>! <br>
        <%= current_user.email %>
        <%= image_tag current_user.image %>
        <h4>session id-<%= session[:user_id] %> </h4>

        <%= form_for(@project) do |f| %>

          <%= f.label :title %>
          <%= f.text_field :title %>

          <%= f.label :description %>
          <%= f.text_field :description %>

          <%= f.submit "Create my Project", class: "btn btn-lg btn-primary" %>
        <% end %>



        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>

  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/mooctracker">M00C Tracker</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right" id="appMenus">
          <li>
            <span class="navbar-form navbar-right">
              <a href="#/app/student" class="btn btn-success">Login</a>
                      <a href="/auth/google_oauth2" id="sign_in">Sign in Google</a>
            </span>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <!-- jumbotron -->
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome to M00C Tracker!</h1>
      <p>MoocTracker helps you track all your online courses in one place!</p>
    </div>
  </div>

  <div class="container-fluid" id="container">

  <div class="col-md-4">
    <h3>
      <span class="glyphicon glyphicon-ok"></span> Organize your Courses &amp; Projects
    </h3>
    <hr>
    <h4>List your courses, add updates, projects and more!</h4>
  </div>

  <div class="col-md-4">
    <h3>
      <span class="glyphicon glyphicon-user"></span> Student Tracking
    </h3>
    <hr>
    <h4>Course Coordinators can track students and see courses, updates, project logs of students.</h4>
  </div>

  <div class="col-md-4">
    <h3>
      <span class="glyphicon glyphicon-phone"></span> Access on Mobile
    </h3>
    <hr>
    <h4>Download M00C Tracker for your Android phone from <a href="#">here</a>.</h4>
  </div>
    
  </div>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
      <hr>
        <p class="pull-right">
        MOOC Tracker is an <a href="https://github.com/Jaaga/mooc-tracker">opensource</a> app built at <a href="http://jaaga.in/">Jaaga</a>.
        </p>
      </div>
    </div>
  </div>
  
  <!-- js libs -->
  <script src="lib/js/jquery.min.js"></script>
  <script src="lib/js/bootstrap.min.js"></script>

</body>
</html>